/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { AccountCreateNestedManyWithoutDocumentsInput } from "./AccountCreateNestedManyWithoutDocumentsInput";
import {
  ValidateNested,
  IsOptional,
  IsEnum,
  IsDate,
  IsJSON,
} from "class-validator";
import { Type } from "class-transformer";
import { EnumDocumentDocumentType } from "./EnumDocumentDocumentType";
import { EnumDocumentStatus } from "./EnumDocumentStatus";
import { GraphQLJSON } from "graphql-type-json";
import { InputJsonValue } from "../../types";
import { UserWhereUniqueInput } from "../../user/base/UserWhereUniqueInput";

@InputType()
class DocumentCreateInput {
  @ApiProperty({
    required: false,
    type: () => AccountCreateNestedManyWithoutDocumentsInput,
  })
  @ValidateNested()
  @Type(() => AccountCreateNestedManyWithoutDocumentsInput)
  @IsOptional()
  @Field(() => AccountCreateNestedManyWithoutDocumentsInput, {
    nullable: true,
  })
  accounts?: AccountCreateNestedManyWithoutDocumentsInput;

  @ApiProperty({
    required: true,
    enum: EnumDocumentDocumentType,
  })
  @IsEnum(EnumDocumentDocumentType)
  @Field(() => EnumDocumentDocumentType)
  documentType!: "Driverlicence" | "Passport" | "GovernmentId";

  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  expiringAt?: Date | null;

  @ApiProperty({
    required: false,
    enum: EnumDocumentStatus,
  })
  @IsEnum(EnumDocumentStatus)
  @IsOptional()
  @Field(() => EnumDocumentStatus, {
    nullable: true,
  })
  status?: "Approved" | "Rejected" | null;

  @ApiProperty({
    required: true,
  })
  @IsJSON()
  @Field(() => GraphQLJSON)
  url!: InputJsonValue;

  @ApiProperty({
    required: false,
    type: () => UserWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => UserWhereUniqueInput)
  @IsOptional()
  @Field(() => UserWhereUniqueInput, {
    nullable: true,
  })
  user?: UserWhereUniqueInput | null;
}

export { DocumentCreateInput };
