services:
  redis:
    container_name: cache
    image: redis
    ports:
      - 6379:6379
    environment:
      CACHE_PORT: ${CACHE_PORT}
      CACHE_TTL: ${CACHE_TTL}
    volumes:
      - redis:/data

volumes:
  redis:
    driver: local
