/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { CreateBankArgs } from "./CreateBankArgs";
import { UpdateBankArgs } from "./UpdateBankArgs";
import { DeleteBankArgs } from "./DeleteBankArgs";
import { BankFindManyArgs } from "./BankFindManyArgs";
import { BankFindUniqueArgs } from "./BankFindUniqueArgs";
import { Bank } from "./Bank";
import { BankService } from "../bank.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => Bank)
export class BankResolverBase {
  constructor(
    protected readonly service: BankService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Bank",
    action: "read",
    possession: "any",
  })
  async _banksMeta(
    @graphql.Args() args: BankFindManyArgs
  ): Promise<MetaQueryPayload> {
    const results = await this.service.count({
      ...args,
      skip: undefined,
      take: undefined,
    });
    return {
      count: results,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Bank])
  @nestAccessControl.UseRoles({
    resource: "Bank",
    action: "read",
    possession: "any",
  })
  async banks(@graphql.Args() args: BankFindManyArgs): Promise<Bank[]> {
    return this.service.findMany(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Bank, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Bank",
    action: "read",
    possession: "own",
  })
  async bank(@graphql.Args() args: BankFindUniqueArgs): Promise<Bank | null> {
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Bank)
  @nestAccessControl.UseRoles({
    resource: "Bank",
    action: "create",
    possession: "any",
  })
  async createBank(@graphql.Args() args: CreateBankArgs): Promise<Bank> {
    return await this.service.create({
      ...args,
      data: args.data,
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Bank)
  @nestAccessControl.UseRoles({
    resource: "Bank",
    action: "update",
    possession: "any",
  })
  async updateBank(@graphql.Args() args: UpdateBankArgs): Promise<Bank | null> {
    try {
      return await this.service.update({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Bank)
  @nestAccessControl.UseRoles({
    resource: "Bank",
    action: "delete",
    possession: "any",
  })
  async deleteBank(@graphql.Args() args: DeleteBankArgs): Promise<Bank | null> {
    try {
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
