/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from '@nestjs/common';
import * as swagger from '@nestjs/swagger';
import * as nestAccessControl from 'nest-access-control';
import * as defaultAuthGuard from '../../auth/defaultAuth.guard';
import { isRecordNotFoundError } from '../../prisma.util';
import * as errors from '../../errors';
import { Request } from 'express';
import { plainToClass } from 'class-transformer';
import { ApiNestedQuery } from '../../decorators/api-nested-query.decorator';
import { TransactionService } from '../transaction.service';
import { AclValidateRequestInterceptor } from '../../interceptors/aclValidateRequest.interceptor';
import { AclFilterResponseInterceptor } from '../../interceptors/aclFilterResponse.interceptor';
import { TransactionCreateInput } from './TransactionCreateInput';
import { TransactionWhereInput } from './TransactionWhereInput';
import { TransactionWhereUniqueInput } from './TransactionWhereUniqueInput';
import { TransactionFindManyArgs } from './TransactionFindManyArgs';
import { TransactionUpdateInput } from './TransactionUpdateInput';
import { Transaction } from './Transaction';
import { AccountFindManyArgs } from '../../account/base/AccountFindManyArgs';
import { Account } from '../../account/base/Account';
import { AccountWhereUniqueInput } from '../../account/base/AccountWhereUniqueInput';
@swagger.ApiBasicAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class TransactionControllerBase {
  constructor(
    protected readonly service: TransactionService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder,
  ) {}

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @nestAccessControl.UseRoles({
    resource: 'Transaction',
    action: 'create',
    possession: 'any',
  })
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Transaction })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async create(
    @common.Body() data: TransactionCreateInput,
  ): Promise<Transaction> {
    return await this.service.create({
      data: data,
      select: {
        amount: true,
        createdAt: true,
        fee: true,
        id: true,
        status: true,
        transactionSubtype: true,
        transactionType: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: 'Transaction',
    action: 'read',
    possession: 'any',
  })
  @common.Get()
  @swagger.ApiOkResponse({ type: [Transaction] })
  @swagger.ApiForbiddenResponse()
  @ApiNestedQuery(TransactionFindManyArgs)
  async findMany(@common.Req() request: Request): Promise<Transaction[]> {
    const args = plainToClass(TransactionFindManyArgs, request.query);
    return this.service.findMany({
      ...args,
      select: {
        amount: true,
        createdAt: true,
        fee: true,
        id: true,
        status: true,
        transactionSubtype: true,
        transactionType: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: 'Transaction',
    action: 'read',
    possession: 'own',
  })
  @common.Get('/:id')
  @swagger.ApiOkResponse({ type: Transaction })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async findOne(
    @common.Param() params: TransactionWhereUniqueInput,
  ): Promise<Transaction | null> {
    const result = await this.service.findOne({
      where: params,
      select: {
        amount: true,
        createdAt: true,
        fee: true,
        id: true,
        status: true,
        transactionSubtype: true,
        transactionType: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`,
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @nestAccessControl.UseRoles({
    resource: 'Transaction',
    action: 'update',
    possession: 'any',
  })
  @common.Patch('/:id')
  @swagger.ApiOkResponse({ type: Transaction })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async update(
    @common.Param() params: TransactionWhereUniqueInput,
    @common.Body() data: TransactionUpdateInput,
  ): Promise<Transaction | null> {
    try {
      return await this.service.update({
        where: params,
        data: data,
        select: {
          amount: true,
          createdAt: true,
          fee: true,
          id: true,
          status: true,
          transactionSubtype: true,
          transactionType: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`,
        );
      }
      throw error;
    }
  }

  @nestAccessControl.UseRoles({
    resource: 'Transaction',
    action: 'delete',
    possession: 'any',
  })
  @common.Delete('/:id')
  @swagger.ApiOkResponse({ type: Transaction })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async delete(
    @common.Param() params: TransactionWhereUniqueInput,
  ): Promise<Transaction | null> {
    try {
      return await this.service.delete({
        where: params,
        select: {
          amount: true,
          createdAt: true,
          fee: true,
          id: true,
          status: true,
          transactionSubtype: true,
          transactionType: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`,
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: 'Account',
    action: 'read',
    possession: 'any',
  })
  @common.Get('/:id/accounts')
  @ApiNestedQuery(AccountFindManyArgs)
  async findManyAccounts(
    @common.Req() request: Request,
    @common.Param() params: TransactionWhereUniqueInput,
  ): Promise<Account[]> {
    const query = plainToClass(AccountFindManyArgs, request.query);
    const results = await this.service.findAccounts(params.id, {
      ...query,
      select: {
        accountNumber: true,
        accountType: true,
        availableBalance: true,
        balance: true,
        createdAt: true,
        currency: true,
        description: true,
        id: true,
        name: true,
        status: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`,
      );
    }
    return results;
  }

  @nestAccessControl.UseRoles({
    resource: 'Transaction',
    action: 'update',
    possession: 'any',
  })
  @common.Post('/:id/accounts')
  async connectAccounts(
    @common.Param() params: TransactionWhereUniqueInput,
    @common.Body() body: AccountWhereUniqueInput[],
  ): Promise<void> {
    const data = {
      accounts: {
        connect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @nestAccessControl.UseRoles({
    resource: 'Transaction',
    action: 'update',
    possession: 'any',
  })
  @common.Patch('/:id/accounts')
  async updateAccounts(
    @common.Param() params: TransactionWhereUniqueInput,
    @common.Body() body: AccountWhereUniqueInput[],
  ): Promise<void> {
    const data = {
      accounts: {
        set: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @nestAccessControl.UseRoles({
    resource: 'Transaction',
    action: 'update',
    possession: 'any',
  })
  @common.Delete('/:id/accounts')
  async disconnectAccounts(
    @common.Param() params: TransactionWhereUniqueInput,
    @common.Body() body: AccountWhereUniqueInput[],
  ): Promise<void> {
    const data = {
      accounts: {
        disconnect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }
}
