/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { ObjectType, Field } from '@nestjs/graphql';
import { ApiProperty } from '@nestjs/swagger';
import { Account } from '../../account/base/Account';
import {
  ValidateNested,
  IsOptional,
  IsInt,
  IsDate,
  IsNumber,
  IsString,
  IsEnum,
} from 'class-validator';
import { Type } from 'class-transformer';
import { EnumTransactionStatus } from './EnumTransactionStatus';
import { EnumTransactionTransactionSubtype } from './EnumTransactionTransactionSubtype';
import { EnumTransactionTransactionType } from './EnumTransactionTransactionType';

@ObjectType()
class Transaction {
  @ApiProperty({
    required: false,
    type: () => [Account],
  })
  @ValidateNested()
  @Type(() => Account)
  @IsOptional()
  accounts?: Array<Account>;

  @ApiProperty({
    required: true,
    type: Number,
  })
  @IsInt()
  @Field(() => Number)
  amount!: number;

  @ApiProperty({
    required: true,
  })
  @IsDate()
  @Type(() => Date)
  @Field(() => Date)
  createdAt!: Date;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsNumber()
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  fee!: number | null;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  id!: string;

  @ApiProperty({
    required: true,
    enum: EnumTransactionStatus,
  })
  @IsEnum(EnumTransactionStatus)
  @Field(() => EnumTransactionStatus, {
    nullable: true,
  })
  status?: 'Successful' | 'Pending' | 'Failed';

  @ApiProperty({
    required: false,
    enum: EnumTransactionTransactionSubtype,
  })
  @IsEnum(EnumTransactionTransactionSubtype)
  @IsOptional()
  @Field(() => EnumTransactionTransactionSubtype, {
    nullable: true,
  })
  transactionSubtype?: 'Fiat' | 'Crypto' | null;

  @ApiProperty({
    required: true,
    enum: EnumTransactionTransactionType,
  })
  @IsEnum(EnumTransactionTransactionType)
  @Field(() => EnumTransactionTransactionType, {
    nullable: true,
  })
  transactionType?: 'Credit' | 'Debit';

  @ApiProperty({
    required: true,
  })
  @IsDate()
  @Type(() => Date)
  @Field(() => Date)
  updatedAt!: Date;
}

export { Transaction };
